name: sui generis
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5966887036338449
title: breaking the cycle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#879190'
    - '#000000'
    - '#e4b55d'
    - '#e32400'
    - '#834700'
  brandStrength: 0
  lightness: 0
  saturation: 0.9747740910388529
  rhythmicContrast: 0
purpose: []
