name: sui generis
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5966887036338449
title: breaking the cycle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e2e2e'
    - '#5b5b5b'
    - '#717171'
    - '#9c9c9c'
    - '#aeaeae'
  brandStrength: 0
  lightness: 0
  saturation: 0.9747740910388529
  rhythmicContrast: 0
purpose: []
