name: Laura Morales
favicon: null
layout_spectrum: 0.6774566019885242
typography_spectrum: 0.5966887036338449
title: breaking the cycle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3211477887816727
  lightness: 0.254796055611223
  saturation: 0.9747740910388529
  rhythmicContrast: 0.028278495417907834
purpose: []
